language: android
sudo: false
jdk:
 - openjdk7
 - oraclejdk7
android:
  components:
    - android-22
    - build-tools-22.0.1
    - extra-android-m2repository
  licenses:
    - android-sdk-license-.+
branches:
 only:
  - master
script:
 - ./gradlew test